-- Task Message Studio: Supabase deployment schema
-- Run this file once in Supabase Dashboard > SQL Editor.

create table if not exists public.tasks (
  id text primary key,
  title text not null default '',
  category text not null default '',
  reward text not null default '',
  time_limit_minutes text not null default '',
  description text not null default '',
  before_text text not null default '',
  after_text text not null default '',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.results (
  id bigint generated by default as identity primary key,
  task_id text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.sessions (
  id bigint generated by default as identity primary key,
  session_id text not null unique,
  task_id text,
  status text not null default 'opened'
    check (status in ('opened', 'started', 'completed', 'abandoned')),
  opened_at timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  last_seen_at timestamptz,
  total_items integer not null default 0,
  attempted_items integer not null default 0,
  correct_items integer not null default 0,
  task_accuracy double precision,
  completion_time_ms bigint,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists results_task_id_idx
  on public.results (task_id);

create index if not exists results_created_at_idx
  on public.results (created_at desc);

create index if not exists sessions_task_id_idx
  on public.sessions (task_id);

create index if not exists sessions_status_idx
  on public.sessions (status);

create index if not exists sessions_created_at_idx
  on public.sessions (created_at desc);

-- These tables are accessed only by the Vercel server-side API using the
-- Supabase service_role key. No browser-facing policy is intentionally added.
alter table public.tasks enable row level security;
alter table public.results enable row level security;
alter table public.sessions enable row level security;
